name: Terraform Apply

permissions:
  id-token: write
# Only run this workflow on commits to the main branch
on:
  push:
    branches:
      - 'main'
      - 'ch6'
jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      # Authenticate to AWS using OIDC
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          # Specify the IAM role to assume -- THIS IS AN OUTPUT FROM THE TERRAFORM OIDC APPLY
          role-to-assume: arn:aws:iam::001857796974:role/github-actions-oidc-memoverrun20231116013335290400000001
          aws-region: us-west-2

      # Run Terraform using HashiCorp's setup-terraform Action
      - uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.1.0
            terraform_wrapper: false
      - name: Terraform Init and Apply
        run: |
            terraform init
            terraform apply -auto-approve